"""Create table stories_schema.stories

Revision ID: 1
Revises: 

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with open('migrations/versions/1.sql') as fo:
        sql = fo.read()

    connection = op.get_bind()
    connection.execute(sql)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute("""
        DROP TABLE stories_schema.stories;
        """)
    # ### end Alembic commands ###
